### PR TITLE
midterm review

### PR DESCRIPTION
**Pull request by MatthewCaseres**

### CODE REVIEW

**Comment by MatthewCaseres** [comment]
Having trouble with installing stuff on mac M1, currently unable to run development version of site for preview. I assume markdown works just like it does in my markdown previewed in VS code.

**Comment by m4ttsch** [comment]
Yeah I had issues when I got my M1 back in 
January.

- Matt Schlenker

**Comment by m4ttsch** [comment]
Are you ready to merge this?

**Comment by MatthewCaseres** [comment]
Yeah now works or tomorrow. By end of day, I'll have another module done. You can do one merge or two, up to you.

**Comment by MatthewCaseres** [comment]
accidental close. With module 9 finished should be good until march 22. ready to merge.

**Comment by m4ttsch** [comment]
Merging! Good work Matt.

**Pull request merged**
