### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by gopalgoel19**
- [X] Fix typos
- [X] Simplify some statememts.

### CODE REVIEW

**Review by m4ttsch — DISMISSED** [review]
Very thorough! Did you pass this through Grammarly or something? Also, I will be reverting European spellings back to American.

**Review by m4ttsch — CHANGES_REQUESTED** [review]
Please revert European spellings back to American (behaviour -> behavior, signalled -> signaled, and any others you may have changed).

**Comment by gopalgoel19** [comment]
Yup used Grammarly. Changed spellings to American English. 

It would be great if someone could do the same for all the files. 😃

**Comment by gopalgoel19** [comment]
Consider creating an issue and adding [Hactoberfest](https://hacktoberfest.digitalocean.com/) as a label. Maybe some kind will be willing to help.

**Review by m4ttsch — APPROVED** [review]

**Comment by m4ttsch** [comment]
Yeah ... it's funny how my notes have progressed over time. OS was my first and, naturally, my worst. I've used Grammarly myself on my notes for my last class (ML4T) and my current class (Simulation), and my notes come out so much better. I'd consider paying someone to update GIOS/CN/IIS because it's no small effort; I just don't have the time for it.

**Comment by gopalgoel19** [comment]
Yeah, that is right. I am taking GIOS this sem. I will try updating GIOS docs as I go along reading those the rest of the semester. Consider it as a thank you for providing these notes fo free. :)

**Comment by m4ttsch** [comment]
Thank you sir. I am happy to review any and all PRs you submit.

- Matt Schlenker

**Pull request merged**
