### PR TITLE
first PR for HCI

### PR DESCRIPTION
**Pull request by MatthewCaseres**

### CODE REVIEW

**Comment by MatthewCaseres** [comment]
This is a bit premature, there are 2 other pages I have to write for this week.

**Comment by m4ttsch** [comment]
Please drop the images from this PR and add them to the GCP bucket.

**Comment by MatthewCaseres** [comment]
found it in my email

**Comment by MatthewCaseres** [comment]
Done I think.

**Comment by m4ttsch** [comment]
Ah, gotcha. Yeah that's a fine place for the pictures for now. Can you do one more thing and just add alt text to each of the images. That's super important for accessibility and SEO and I want to require that on images going forward.

**Comment by m4ttsch** [comment]
Closing after offline discussion.

**Pull request closed without merging**
