### PR TITLE
CS-6250 Computer Networks - version 2

### PR DESCRIPTION
**Pull request by joshkuun**
A previous iteration of the Computer Networks course is currently the only OMSCS Notes that is available. While these can be helpful and still teach useful concepts, the old lectures notes do not cover the same material. Students are expected to study and use the updated content moving forward.

**Changes**
This pull request provides my notes for the second iteration of this course, which includes the following topics:
- The course begins with an overview of the history of the Internet and its current architecture, teaches how basic computer networking algorithms and protocols work, and explores router design and functionalities. 
- Then the course takes a more in-depth look at Software Defined Networking technologies and how to achieve multiple tasks by applying various Internet measurements and analytics. 
- The final part of the course explores current issues related to networking such as Content Delivery Network (CDN), overlay networks, cloud computing, wireless and mobile networks, and the Internet of Things.

**For Reviewers**
The different versions are contained in two separate directories (`version-1`, `version-2`). Please let me know if there is another directory structure that should be used for differentiating between versions. In addition, I've added all of the images necessary for the updated notes to the `computer-networks/version-2/assets`. I probably need temporary access to the storage instance that is being used to host images, but let me know if there is another process for adding images.

### CODE REVIEW

**Comment by m4ttsch** [comment]
This is... incredible. Do your additions cover the content for the entire course as it currently exists or is this a work in progress?

**Comment by joshkuun** [comment]
@m4ttsch Thanks! To answer your question, this covers the content for the entire course.

**Comment by m4ttsch** [comment]
Send me an email please, matt@omscs-notes.com and we can talk about how to get this merged in. You will need access to my GCP bucket to upload the images.

**Comment by JHBalaji** [comment]
@m4ttsch when you merge them please keep the v1 notes in the website. Probably CN_v1 or something.

**Comment by christiandavidturner** [comment]
Hey! Will these be ready for the Fall? I'm thinking of taking CN first and just came across this.

**Comment by m4ttsch** [comment]
Merging this is now. Thanks @joshkuun. This should be on the site shortly!

**Pull request merged**
